[package]
name = "aoc2019"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.2"
modinverse = "0.1.1"
mod_exp = "1"
num = "0.4.0"
peg = "0.8.0"
